#!/usr/bin/env bash
# Local dev run for aaa-hub server.
#
# Boots the Axum server with cargo incremental rebuild against a self-contained
# dev profile under target/server-dev/ (config.toml + sqlite db + uploads +
# artifacts), so it never collides with a production /etc/aaa-hub install.
# Use this for fast iteration; for a release tarball see
# scripts/server/build-release.sh.
#
# Usage:  ./scripts/server/dev.sh [extra args forwarded to `cargo run`]
#
# Inputs honoured from the environment:
#   AAA_HUB_CONFIG  Override the auto-generated dev config path. If set,
#                   this script will skip the auto-bootstrap step entirely
#                   and just exec cargo run with that config.
#   RUST_LOG        Defaults to "info,aaa_hub=debug" if unset.

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd -- "$SCRIPT_DIR/../.." && pwd)"

DEV_DIR="$ROOT_DIR/target/server-dev"
DEFAULT_CFG="$DEV_DIR/config.toml"
CFG="${AAA_HUB_CONFIG:-$DEFAULT_CFG}"

if [ ! -f "$CFG" ]; then
  if [ "$CFG" != "$DEFAULT_CFG" ]; then
    echo "error: AAA_HUB_CONFIG=$CFG does not exist." >&2
    exit 1
  fi
  echo ">> first run, materialising dev config at $CFG"
  mkdir -p "$DEV_DIR/artifacts" "$DEV_DIR/uploads"
  cat >"$CFG" <<EOF
# Auto-generated by scripts/server/dev.sh on first run.
# Safe to edit; this file is gitignored under target/.

[server]
bind = "127.0.0.1:8787"
public_url = "http://127.0.0.1:8787"
data_dir = "$DEV_DIR"
admin_token = "dev-admin-token"

[updates]
artifacts_dir = "$DEV_DIR/artifacts"
pubkey = "dev-placeholder-pubkey"

[uploads]
dir = "$DEV_DIR/uploads"
max_attachment_bytes = 10485760
allowed_mime = ["image/png", "image/jpeg"]

[notify.email]
enabled = false
smtp_host = ""
smtp_port = 587
smtp_user = ""
smtp_password = ""
from = ""
to = []

[ratelimit]
feedback_per_ip_per_hour = 30
manifest_per_ip_per_minute = 60
EOF
fi

# sqlx::migrate!("./migrations") is baked relative — CWD must be server/.
cd "$ROOT_DIR/server"

export AAA_HUB_CONFIG="$CFG"
export RUST_LOG="${RUST_LOG:-info,aaa_hub=debug}"

echo ">> AAA_HUB_CONFIG=$AAA_HUB_CONFIG"
echo ">> cargo run -p aaa-hub $*"
exec cargo run -p aaa-hub "$@"
